#!/usr/bin/env python
from faker import Faker
from faker.providers import DynamicProvider


fake = Faker()

team_names = [
  "Accrington Stanley",
  "A.F.C. Bournemouth",
  "A.F.C. Wimbledon",
  "Arsenal",
  "Aston Villa F.C.",
  "Barnsley F.C.",
  "Barrow AFC",
  "Birmingham City F.C.",
  "Blackburn Rovers F.C.",
  "Blackpool F.C.",
  "Bolton Wanderers F.C.",
  "Bradford City A.F.C.",
  "Brentford F.C.",
  "Brighton & Hove Albion F.C.",
  "Bristol City F.C.",
  "Bristol Rovers F.C.",
  "Burnley F.C.",
  "Burton Albion F.C.",
  "Bury F.C.",
  "Cambridge United F.C.",
  "Cardiff City F.C.",
  "Carlisle United F.C.",
  "Charlton Athletic F.C.",
  "Chelsea F.C.",
  "Cheltenham Town F.C.",
  "Colchester United F.C.",
  "Coventry City F.C.",
  "Crawley Town F.C.",
  "Crewe Alexandra F.C.",
  "Crystal Palace F.C.",
  "Derby County F.C.",
  "Doncaster Rovers F.C.",
  "Everton F.C.",
  "Exeter City F.C.",
  "Fleetwood Town F.C.",
  "Forest Green Rovers",
  "Fulham F.C.",
  "Gillingham F.C.",
  "Grimsby Town F.C.",
  "Huddersfield Town A.F.C.",
  "Hull City A.F.C.",
  "Ipswich Town F.C.",
  "Leeds United F.C.",
  "Leicester City F.C.",
  "Lincoln City F.C.",
  "Leyton Orient F.C.",
  "Liverpool F.C.",
  "Luton Town F.C.",
  "Macclesfield Town F.C.",
  "Manchester City F.C.",
  "Manchester United F.C.",
  "Mansfield Town F.C.",
  "Middlesbrough F.C.",
  "Millwall F.C.",
  "MK Dons",
  "Morecambe",
  "Newcastle United",
  "Newport County A.F.C.",
  "Norwich City F.C.",
  "Northampton Town",
  "Nottingham Forest F.C.",
  "Notts County F.C.",
  "Oldham Athletic A.F.C.",
  "Oxford United F.C.",
  "Peterborough United F.C.",
  "Plymouth Argyle F.C.",
  "Port Vale F.C.",
  "Portsmouth F.C.",
  "Preston North End F.C.",
  "Queens Park Rangers F.C.",
  "Reading F.C.",
  "Rochdale A.F.C.",
  "Rotherham United F.C.",
  "Salford City F.C.",
  "Scunthorpe United F.C.",
  "Sheffield United F.C.",
  "Sheffield Wednesday F.C.",
  "Shrewsbury Town F.C.",
  "Southampton F.C.",
  "Southend United F.C.",
  "Stevenage F.C.",
  "Stoke City F.C.",
  "Sunderland A.F.C.",
  "Sutton United F.C.",
  "Swansea City A.F.C.",
  "Swindon Town F.C.",
  "Torquay United F.C.",
  "Tottenham Hotspur F.C.",
  "Tranmere Rovers F.C.",
  "Walsall F.C.",
  "Watford F.C.",
  "West Bromwich Albion F.C.",
  "West Ham United F.C.",
  "Wigan Athletic F.C.",
  "Woking F.C.",
  "Wolverhampton Wanderers F.C.",
  "Wrexham F.C.",
  "Wycombe Wanderers F.C.",
  "Yeovil Town F.C.",
]

team_name_provider = DynamicProvider(
    provider_name="team_name",
    elements=team_names
)

player_type_provider = DynamicProvider(
    provider_name="player_type",
    elements=["POR", "DEF", "MED", "DEL"]
)

fake.add_provider(team_name_provider)
fake.add_provider(player_type_provider)
